smart_events:
  github_url: 'https://github.com/ministrycentered/smart-events'
  tracker_api_token: 87b8a49b7c00bd80e4e310fd02b5db77
  tracker_project_id: 15907
  ref: refs/heads/master
  user_api_tokens:
    jonathan:
      email: jonathan.vaught@gmail.com
      tracker_api_token: 87b8a49b7c00bd80e4e310fd02b5db77
